### ISSUE TITLE
any way to sign in without a browser?

### ISSUE THREAD

**Issue by eengad** [Exafunction/codeium.el#10]
I use emacs in WSL and get:
Error running timer ‘codeium-defer-until-no-input’: (error "No usable browser found")

Any way to go around it?

**Comment by fortenforge** [comment]
When it asks you if you want to open the URL you can say "no". Then you should be able to use `M-x codeium-kill-last-auth-url` to copy the login URL to your kill ring and then visit that URL manually.

**Comment by Alan-Chen99** [comment]
Actually I'm on wsl too and it works fine; will look into it

**Comment by Alan-Chen99** [comment]
`browser-url` seems to use `xdg-open` for me; Can you try to see if that works on the terminal?

**Comment by Alan-Chen99** [comment]
close this since not a problem of codeium.el; reopen if needed
