### ISSUE TITLE
Stopping codeium integration and restarting

### ISSUE THREAD

**Issue by ghmon** [Exafunction/codeium.el#106]
Due to low computer memory i want sometimes to temporarily stop codeium integration and server, and restart later, both from within emacs, without ending emacs. codeium is loaded on startup.

I have found a solution, see below - but it is very ugly. Is there a better, even documented way?

```
(defun walk-buffers (fn)
  "Execute function FN in all buffers."
  (dolist (buffer (buffer-list))
    (with-current-buffer buffer
      (funcall fn))))

(defun codeium-server-off()
  (interactive)
  (shell-command "pkill codeium")
  (remove-hook 'completion-at-point-functions 'codeium-completion-at-point)
  (walk-buffers
   '(lambda ()
      (remove-hook 'completion-at-point-functions 'codeium-completion-at-point t))))

(defun codeium-server-on()
  (interactive)
    (walk-buffers
   '(lambda ()
      (add-hook 'completion-at-point-functions #'codeium-completion-at-point))))


```

**Comment by fortenforge** [comment]
We don't have any documented way of doing this.

**Comment by ghmon** [comment]
Ok; described way works, at least using one window with several buffers. I close the issue.
