### ISSUE TITLE
Not seeing suggestion in `C++` (lsp + company)

### ISSUE THREAD

**Issue by apmanol** [Exafunction/codeium.el#20]
Hello all,

trying to play around with this awesome software, bad it doesn't work in `C++` mode with `lsp` enabled. 

A snippet of the `.emacs` can be found https://gist.github.com/apmanol/6ab0bb12174d3f1fc9b7b2ff1e4fa909 it's a setup with `lsp + company + company lsp`.

The server seems to work  as it seems in the [logs](https://gist.github.com/apmanol/7b073ee7dfb74e9880b784d745c1a9d4) and in the `diagnose` but autocomplete doesn't work. 
Furthermore, without `lsp mode` i.e. scratch, I can see suggestions and server communication.

```
completion-at-point-functions is a variable defined in ‘minibuffer.el’.

Its value is
(codeium-completion-at-point tags-completion-at-point-function)
```

Probably, I miss something, but I can't find out anything. 

thanks for any tips.

**Comment by Alan-Chen99** [comment]
whats the value of `codeium-completion-at-point` local to the buffer you are completing in?
If you instead see lsp completions, then you need to manually reorder the priorities (probably on your mode hook). If you want to see both I recommend `cape-super-capf`

**Comment by akhil3417** [comment]
a better way would be to prepend codeium-completion-at-point  to current value of completion-at-point-functions , different modes have different buffer local values for completion , if you are hooking it maybe add an delay of few seconds to the following function.

`         (defun add-codeium-completion ()
           (interactive)
           (setq completion-at-point-functions
                 (cons 'codeium-completion-at-point
                 completion-at-point-functions))
           (setq-local company-frontends
                       '(company-pseudo-tooltip-frontend
                       company-preview-frontend))
           (setq company-minimum-prefix-length 0))


         ;; (add-hook 'python-mode-hook
         ;;           (lambda)
         ;;           (run-with-timer 2 nil
         ;;                           (lambda()
         ;;                             (add-hook 'post-command-hook
                                        #'add-codeium-completion))))


         (defun remove-codeium-completion ()
           (interactive)
           (setq completion-at-point-functions
                 (delete 'codeium-completion-at-point
                 completion-at-point-functions))
           (setq company-frontends
                       '(company-box-frontend company-preview-frontend))
           (setq company-minimum-prefix-length 2))

`

**Comment by Alan-Chen99** [comment]
While what @akhil3417 have is fine, you probably want something much less aggressive, like
```
(add-hook 'python-mode-hook
    (lambda () (run-with-timer 2 nil #'add-codeium-completion)))
```
You would otherwise have a very hard time of turning codeium off.

**Comment by Alan-Chen99** [comment]
Also, if you don't have any other deferred things, you shouldn't need the timer.

**Comment by apmanol** [comment]
> whats the value of `completion-at-point-functions` local to the buffer you are completing in? If you instead see lsp completions, then you need to manually reorder the priorities (probably on your mode hook). If you want to see both I recommend `cape-super-capf`
> 
> Edit: I meant "completion-at-point-functions" instead of "codeium-completion-at-point"

```Its value is
(lsp-completion-at-point codeium-completion-at-point tags-completion-at-point-function)
Local in buffer xxx.cpp```

**Comment by apmanol** [comment]
I removed the `company-lsp` because it isn't supported anymore, from `lsp-mode` and now `codeium` is autocompleting only the comments in the code! That is some progress.

**Comment by apmanol** [comment]
I replaced the company with `corfu` and `cape + capf`  and things are much better now.

Would you like to leave the bug open, since the setup with the `company` didn't go very smoothly?

**Comment by fortenforge** [comment]
Closing this since your issue is resolved. I created a new issue to track the particular problem you had with company.
