### ISSUE TITLE
code completion not working as expected

### ISSUE THREAD

**Issue by akhil3417** [Exafunction/codeium.el#22]
Here are some of the logs in codeium-log 

```
E0322 08:17:09.691283 30886 prompt.go:142] Error checking for empty block node start: UseTreeSitter: astNodeCaseUnspecified or node is null
E0322 08:17:09.691296 30886 prompt.go:150] Failed to determine if multiline completions should be requested.
E0322 08:17:26.507256 30886 prompt.go:478] Error getting sibling functions: UseTreeSitter: no function parent found at offset 26

```

Is this expected behaviour?

These three errors pretty consistent in my case.

**Comment by fortenforge** [comment]
These are not really errors per se and they shouldn't affect the plugin's functionality at all. You can safely ignore them (and on our end we should probably stop logging them as errors or at all).
