### ISSUE TITLE
[Question] How can I use `codeium` cycle completions alongside with GitHub Copilot?

### ISSUE THREAD

**Issue by lroolle** [Exafunction/codeium.el#27]
# How can I use `codeium` cycle completions alongside with GitHub Copilot?

I'm using GitHub Copilot right now, and I want to use codeium cycle completions alongside with it. 

The Copilot extension I'm using is https://github.com/zerolfx/copilot.el.

How can I make it? Thanks

**Comment by fortenforge** [comment]
I believe that this is not easily done. Codeium provides a `completion-at-point-functions` backend, which means that its completions are rendered via a frontend like corfu or company-mode. But the copilot extension you are using is directly rendering the completions itself (bypassing these completion frontends). So they can't integrate well.

**Comment by lroolle** [comment]
> I believe that this is not easily done. Codeium provides a `completion-at-point-functions` backend, which means that its completions are rendered via a frontend like corfu or company-mode. But the copilot extension you are using is directly rendering the completions itself (bypassing these completion frontends). So they can't integrate well.

Yes it works! like this:
![image](https://user-images.githubusercontent.com/14071051/231628292-a5853b35-b19d-4694-890f-bed90a7f1434.png)

Thank you.
