### ISSUE TITLE
Installation Instructions Are Incomplete

### ISSUE THREAD

**Issue by FrankDMartinez** [Exafunction/codeium.el#29]
After installing manually, because MELPA doesn't have Codeium and I am unaware of any other package installation which does, I attempted to perform `M-x codeium-install`. Emacs does not recognize `codeium-install`.

What are the instructions missing?

**Comment by ZWindL** [comment]
Do you have the command `M-x codeium-init`? Based on my experience, the `-init` does the same job.

**Comment by fortenforge** [comment]
We've written down various ways to actually install the package [here](https://github.com/Exafunction/codeium.el#-installation-options). MELPA isn't an option unfortunately, but most other package managers should work. You need to install the Codeium package before performing `M-x codeium-install`.

**Comment by fortenforge** [comment]
Closing due to staleness. Please feel free to re-open if you are still experiencing issues.

**Comment by theRunCom** [comment]
Maybe you should add `(require 'codeium)` after `(add-to-list 'load-path "~/.emacs.d/elpa/codeium.el")`.
I met the same situation as you. There was no `codeium-install` when I pressed the M-x, but I use it to solve!
