### ISSUE TITLE
Flaky behavior in Python

### ISSUE THREAD

**Issue by lambdaofgod** [Exafunction/codeium.el#30]
I've managed to start codeium with company using akhil3417's suggestion in #20 

It fails fast though, I've encountered 2 types of errors in log:

```
E0501 13:29:51.913056 1465117 prompt.go:142] Error checking for empty block node start: UseTreeSitter: no start keyword children found
E0501 13:29:51.913079 1465117 prompt.go:150] Failed to determine if multiline completions should be requested.

```

And
`E0501 13:33:33.260453 1477885 prompt.go:478] Error getting sibling functions: UseTreeSitter: no function parent found at offset 1332
`

**Comment by fortenforge** [comment]
None of those messages are real errors and we probably should not be logging them at all. These should not impact the ability of Codeium to provide completions. Are you able to see and accept code completions?
