### ISSUE TITLE
Very slow!

### ISSUE THREAD

**Issue by PineTreePizza** [Exafunction/codeium.el#31]
Not sure if it's my hardware or just the implementation of codeium in emacs but with the default config the completions come in very slowly, and sometimes I feel like if they do come in they never get suggested to me, the issue with speed arose when I saw a friend use codeium in pycharm and it was blazing fast.

**Comment by fortenforge** [comment]
You should be seeing suggestions at about the same speed as the gif in the README: https://github.com/Exafunction/codeium.el

The gif wasn't sped up or altered in any way. (That said, network latency can cause completions to come in more slowly; United States users should see the fastest completions, and users in Asia should see slower ones).

Your hardware shouldn't matter too much in terms of the speed of completions unless your computer is unusually bad. The likelier candidate is something is wrong / bad with the way your emacs completion providers are configured. Do you have any other completion backends?

**Comment by PineTreePizza** [comment]
> 

hmm

**Comment by PineTreePizza** [comment]
hmm im not sure whats causing it then (mb accidentally closed the issue)
it seems that im getting the completions in the logs but they dont seem to reach me.
I need to test, maybe lsp-mode or other completion backends could be messing with it.

**Comment by PineTreePizza** [comment]
so i was doing a bit of testing and I'm not sure what this means.
![image](https://user-images.githubusercontent.com/77921296/235552305-b8eefe9a-cc0c-4f49-a591-9a831f7d3783.png)

**Comment by fortenforge** [comment]
None of the Treesitter errors or any errors in prompt.go are real failures; you can safely ignore these.

From what I'm seeing, the GetCompletions RPC is taking 0.46 / 0.13 seconds. This isn't super fast but is well within the normal range. Do your completions take much longer than this to actually show up?

**Comment by PineTreePizza** [comment]
I got it, so the completions work as intended just for some reason they don't show up as previews for some reason. I pressed tab to test and the completion came up, there is just no visual to it hmm.

**Comment by PineTreePizza** [comment]
yeah what im seeing is basically it generates it but i cant see the completion, also i can auto complete like 10% of the time from the genrated completion for some reason hmmm

**Comment by fortenforge** [comment]
My best guess is that there is some other completion backend that is taking precedence over Codeium. What is the order of your completion-at-point-functions variable? Is Codeium at the front?

**Comment by PineTreePizza** [comment]
How do I check my completion-at-point-functions variable? I'm semi-new to emacs don't have all the quirks ironed out mb

**Comment by PineTreePizza** [comment]
oh, just checked, right now the only thing is codeium in there, and this tags-completion-at-point not sure what that is

**Comment by PineTreePizza** [comment]
bruteforced it
kinda works, not as fast as the video but eh, at least it works!

**Comment by fortenforge** [comment]
Can you explain what you did? What does "bruteforced it" mean?

**Comment by PineTreePizza** [comment]
its very funny cause I don't remember i can check my init.el and see i was very sleep deprived lol
