### ISSUE TITLE
Building the language server?  Support for OSs other than closed source Windon't, fakintosh/crabapple, and ...linux?

### ISSUE THREAD

**Issue by anoduck** [Exafunction/codeium.el#63]
The Emacs package is setup and ready to go. Except, I need to build the codeium language server for my BSD system. Where is it? Or is it closed source?

**Comment by fortenforge** [comment]
It's closed source.

**Comment by anoduck** [comment]
@fortenforge So, guessing that means only the big three are supported (windows, mac, and linux), everyone else is SOL. OK, thanks.
