### ISSUE TITLE
Language server port file not found after 60 seconds

### ISSUE THREAD

**Issue by zhaofanxing** [Exafunction/codeium.el#80]
windows11,idea2023.2.3,codeium 1.2.4 
I found the target file on the disk "C:\Users\user1\AppData\Roaming\JetBrains\IntelliJIdea2023.2\plugins\codeium\a3052dba993afbbe90c01c0591b1f5dc198b5158\language_server_windows_x64.exe"
But the plugin alerted me that Language server port file not found after 60 seconds

**Comment by gwhip70** [comment]
I received a similar error and the folder exists, not sure what it is expecting.
Language server port file not found in C:\Users\I2\AppData\Local\Temp\74ac8034-be8f-46ad-a068-a59b4722c752\codeium\manager after 60s

**Comment by blykt** [comment]
I see the same problem on Linux (Fedora 38) using VSCode 1.87.2 (Codeium Enterprise Edition v1.6.13):
Language server port file not found in /tmp/a110755d-02dd-41d6-8648-367b9ef919d0/codeium/manager after 60s

**Comment by blankhtml** [comment]
Same with me using MacOS Sonoma 14.1.2

**Comment by rdattilo** [comment]
Same, but I only seem to experience this when im using a dev container.

**Comment by chunyue** [comment]
I face the same problem. I use IntelliJ IDEA 2024.1.1 (Ultimate Edition)

**Comment by AliAsgharGill** [comment]
**### Install and uninstall 3 to 4 time it will start working.**

**Comment by biisal** [comment]
> **### Install and uninstall 3 to 4 time it will start working.**

what to install or uninstall ?

**Comment by robinoberson** [comment]
Same problem, any solution?

**Comment by johe123qwe** [comment]
Same problem

**Comment by fortenforge** [comment]
Temporary solution is to downgrade to 1.8.34. We'll soon have a new release out that fixes this.

**Comment by chunyue** [comment]
My version of codeium Intellij plugin is 1.8.31, ( Windows 11  )
and I can't find way to downgrade.
Maybe just wait for the new version released.

**Comment by AliAsgharGill** [comment]
> > **### Install and uninstall 3 to 4 time it will start working.**
> 
> what to install or uninstall ?

Codeium Install and Uninstall 3 to 4 times

**Comment by hermes85pl** [comment]
> Temporary solution is to downgrade to 1.8.34. We'll soon have a new release out that fixes this.

@fortenforge, how soon is soon? It looks like the development of this extension effectively stopped on 1.8.34 for us.

**Comment by fortenforge** [comment]
This issue isn't specific to the emacs extension; the issue was fixed on the language server. Are you still seeing this issue?

**Comment by hermes85pl** [comment]
> This issue isn't specific to the emacs extension; the issue was fixed on the language server. Are you still seeing this issue?

@fortenforge, I can see. I don't know how you came up with emacs in the first place. Personally I've been using VSCode and tried Vim. For the latter it didn't work at all and I have given up not to waste more time. For the former it doesn't work with the latest version, but I tried reverting to and old one as you previously suggested and this worked.

**Comment by hermes85pl** [comment]
I cleaned up local folders used by the extension and updated again to the latest and so far it seems to work. I will be observing it.

**Comment by fortenforge** [comment]
FYI the reason I mentioned emacs is that this issue is being raised on the Codeium Emacs extension repository.

Issues with the VSCode extension should be reported in our discord or emailed to vscode@codeium.com.

**Comment by rarahim75** [comment]
> Temporary solution is to downgrade to 1.8.34. We'll soon have a new release out that fixes this.

Where do I find this plugin version for Visual Studio IDE?

**Comment by mryasinize** [comment]
> I cleaned up local folders used by the extension and updated again to the latest and so far it seems to work. I will be observing it.

Which folders to clean for windows?

**Comment by legeidaa** [comment]
Same for me and nothing helps. Deleted user/.codeium, replaced language_server_windows_x64.exe, but still  "Language server port file..."

**Comment by m3c-ode** [comment]
I'm a mac user and I am facing the same issue on VSCode. If it helps the build is macOS 26.3 (Tahoe beta, Build 25D2125)
