### ISSUE TITLE
Codeium with auth-source and password-store (aka pass)

### ISSUE THREAD

**Issue by abcdw** [Exafunction/codeium.el#84]
To obtain a token from password store, you can use the following snippet of code: 

```emacs-lisp
(with-eval-after-load 'codeium
  (require 'auth-source)
  (setq-default
   codeium/metadata/api_key
   (funcall (plist-get
             (nth 0 (auth-source-search :host "codeium.ai"))
             :secret))))
```                    

Probably it should be a better implementation or support on codeium side.

**Comment by bbigras** [comment]
Yeah it would be nice if codeium had something like gptel where you can set `gptel-api-key` to the key string and the default is to use a function to fetch the key from the auth-source.

https://github.com/karthink/gptel/blob/8ba07d042c11cb65ebce69fc1dc069905ec00e5e/gptel.el#L156-L166

https://github.com/karthink/gptel/blob/8ba07d042c11cb65ebce69fc1dc069905ec00e5e/gptel.el#L498-L512
