### ISSUE TITLE
Any chance of supporting BSD?

### ISSUE THREAD

**Issue by anoduck** [Exafunction/codeium.el#87]
I use this on linux with vscode and it rocks, but would like to have it run on my desktop which is OpenBSD. Any chance of providing support for it?

**Comment by fortenforge** [comment]
No plans unfortunately.

**Comment by anoduck** [comment]
@fortenforge Codeium is utterly mind blowing sometimes, this brings great sadness to an already weary heart, but I appreciate the response. I will have to learn to move on somehow... :cry: Po Po Po... :sob:
