### ISSUE TITLE
language_server_windows_x64.exe Memory Leak (VS Code 1.84.2)

### ISSUE THREAD

**Issue by RubikSW** [Exafunction/codeium.el#90]
I don't have any information yet on how to reproduce this other than leave VSCode open with 2 or 3 windows for ~30 minutes and observe 100% memory usage from language_server_windows_x64.exe.

Latest version of Codeium for VSCode.

Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by fortenforge** [comment]
This repository is for the Emacs plugin. Please raise this issue either in https://github.com/Exafunction/codeium or our discord.
